name: capstone

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytest
  - matplotlib
  - seaborn
  - ipykernel
  - pytorch=2.13
  - pip
  - pip:
      - datasets>=3.1
      - transformers>=5.4,<6
      - accelerate>=0.23
      - sae-lens==6.49.1
